### ISSUE TITLE
Update aravis and ion-kit binaries

### ISSUE THREAD

**Issue by fixstars-sonali** [Sensing-Dev/sensing-dev-installer#20]
Build sensing dev with following dependencies
```
libraries:
  aravis:
    name: aravis
    action: build # can be 'download', 'build', or 'use_existing'
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/Aravis-0.8.25-patched-0fec828.zip"
    pkg_sha: "233bcac1f50fbd2aea6f9572171a77e0655386709a7813ef993b05e3168c6e8f"
    version: "0.8.25"

  pygobject:
    name: pygobject
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/pygobject-3.42.2.zip"
    pkg_sha: "eea9465b7cbf1420ee3b3d8a78f6cfa3feeff89ffade7ab1874ebb25d7078037"
    version: "3.42.2"

  ion_kit:
    name: ion-kit
    pkg_url: "https://ion-kit.s3.us-west-2.amazonaws.com/dependencies/ion-kit-0.3.4-win64-patched-a977ada.zip"
    pkg_sha: "6b95ab18a4f0cff8fd124aaeb91937dc844ed912586c0d56cfd7b00adafc3a04"
    version: "0.3.4"

  opencv:
    name: opencv
    pkg_url: "https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-vc14_vc15.exe"
    pkg_sha: "cac31973cd1c59bfe9dc926acbde815553d23662ea355e0414b5e50d8f8aa5a8"
    version: "4.5.5"
```
